spring:
  application:
    name: p1

  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: amlesh98182199@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

b:
  url: http://127.0.0.1:8000

cloudinary:
  cloud-name: dmmwgljzl
  api-key: 561432715961953
  api-secret: r_mD11p_-7_KEPye8EfA5YB8Bok

jwt:
  secret: abcdefghijklmnopqrstuvwxyz123456
  expiration: 86400000
  expiration-ms: 86400000
  issuer: attendance-app
  token-type: Bearer

logging:
  level:
    org.springframework.mail: DEBUG